export const danhSachTinhChatDuAn = [
  {
    name: "Nhà máy điện hạt nhân",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có yêu cầu chuyển mục đích sử dụng đất rừng đặc dụng từ 50 ha trở lên",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có yêu cầu chuyển mục đích sử dụng đất rừng phòng hộ đầu nguồn từ 50 ha trở lên",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có yêu cầu chuyển mục đích sử dụng đất rừng phòng hộ biên giới từ 50 ha trở lên",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có yêu cầu chuyển mục đích sử dụng đất rừng chắn gió từ 500 ha trở lên",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có yêu cầu chuyển mục đích sử dụng đất rừng chắn cát bay từ 500 ha trở lên",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có yêu cầu chuyển mục đích sử dụng đất rừng phòng hộ chắn sóng từ 500 ha trở lên",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư lấn biển từ 500 ha trở lên",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có yêu cầu chuyển mục đích sử dụng đất trồng lúa nước từ 02 vụ trở lên với quy mô từ 500 ha trở lên",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có yêu cầu di dân tái định cư từ 20.000 người trở lên ở miền núi, từ 50.000 người trở lên ở vùng khác",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có yêu cầu áp dụng cơ chế, chính sách đặc biệt cần được Quốc hội quyết định",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có yêu cầu chuyển mục đích sử dụng đất rừng đặc dụng dưới 50 ha",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có yêu cầu chuyển mục đích sử dụng đất rừng phòng hộ đầu nguồn dưới 50 ha",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có yêu cầu chuyển mục đích sử dụng đất rừng phòng hộ biên giới dưới 50 ha",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có yêu cầu chuyển mục đích sử dụng đất rừng chắn gió dưới 500 ha",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có yêu cầu chuyển mục đích sử dụng đất rừng chắn cát bay dưới 500 ha",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có yêu cầu chuyển mục đích sử dụng đất rừng phòng hộ chắn sóng dưới 500 ha",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư lấn biển dưới 500 ha",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án rừng sản xuất dưới 1.000 ha",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có yêu cầu chuyển mục đích sử dụng đất trồng lúa nước từ 02 vụ trở lên với quy mô dưới 500 ha",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có yêu cầu di dân tái định cư từ 10.000 người trở lên ở miền núi, từ 20.000 người trở lên ở vùng khác",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư xây dựng mới: cảng hàng không, sân bay; đường cất hạ cánh của cảng hàng không, sân bay; nhà ga hành khách của cảng hàng không quốc tế; nhà ga hàng hóa của cảng hàng không, sân bay có công suất từ 01 triệu tấn/năm trở lên",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư mới kinh doanh vận chuyển hành khách bằng đường hàng không",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư xây dựng mới: bến cảng, khu bến cảng thuộc cảng biển đặc biệt; bến cảng, khu bến cảng có quy mô vốn đầu tư từ 2.300 tỷ đồng trở lên thuộc cảng biển loại I",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư chế biến dầu khí",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có kinh doanh đặt cược, ca-si-nô (casino), trừ kinh doanh trò chơi điện tử có thưởng dành cho người nước ngoài",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư xây dựng nhà ở để bán, cho thuê, cho thuê mua có quy mô sử dụng đất từ 300 ha trở lên hoặc quy mô dân số từ 50.000 người trở lên",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án khu đô thị có quy mô sử dụng đất từ 300 ha trở lên hoặc quy mô dân số từ 50.000 người trở lên",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư xây dựng và kinh doanh kết cấu hạ tầng khu công nghiệp, khu chế xuất",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư của nhà đầu tư nước ngoài trong lĩnh vực kinh doanh dịch vụ viễn thông có hạ tầng mạng, trồng rừng, xuất bản, báo chí",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư đồng thời thuộc thẩm quyền chấp thuận chủ trương đầu tư của từ 02 Ủy ban nhân dân cấp tỉnh trở lên",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư khác thuộc thẩm quyền chấp thuận chủ trương đầu tư hoặc quyết định đầu tư của Thủ tướng Chính phủ theo quy định của pháp luật",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có đề nghị Nhà nước giao đất, cho thuê đất không thông qua đấu giá quyền sử dụng đất, không thông qua đấu thầu lựa chọn nhà đầu tư",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư của hộ gia đình, cá nhân có nhu cầu chuyển mục đích sử dụng đất trồng lúa, đất rừng phòng hộ, đất rừng đặc dụng sang mục đích khác để thực hiện dự án đầu tư",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư có đề nghị Nhà nước giao đất, cho thuê đất không thuộc trường hợp nhận chuyển nhượng quyền sử dụng đất, tài sản gắn liền với đất",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án có đề nghị chuyển đất trồng lúa sang đất trồng cây lâu năm, đất trồng rừng, đất nuôi trồng thủy sản, đất làm muối",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án có đề nghị chuyển đất trồng cây hàng năm khác sang đất nuôi trồng thủy sản nước mặn, đất làm muối, đất nuôi trồng thủy sản dưới hình thức ao, hồ, đầm",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án có đề nghị chuyển đất rừng đặc dụng, đất rừng phòng hộ, đất rừng sản xuất sang sử dụng vào mục đích khác trong nhóm đất nông nghiệp",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án có đề nghị chuyển đất nông nghiệp sang đất phi nông nghiệp",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án có đề nghị chuyển đất phi nông nghiệp được Nhà nước giao đất không thu tiền sử dụng đất sang đất phi nông nghiệp được Nhà nước giao đất có thu tiền sử dụng đất hoặc thuê đất",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án có đề nghị chuyển đất phi nông nghiệp không phải là đất ở sang đất ở",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Chuyển đất xây dựng công trình sự nghiệp, đất sử dụng vào mục đích công cộng có mục đích kinh doanh, đất sản xuất, kinh doanh phi nông nghiệp không phải là đất thương mại, dịch vụ sang đất thương mại, dịch vụ; chuyển đất thương mại, dịch vụ, đất xây dựng công trình sự nghiệp sang đất cơ sở sản xuất phi nông nghiệp",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư xây dựng nhà ở để bán, cho thuê, cho thuê mua có quy mô sử dụng đất dưới 300 ha hoặc quy mô dân số dưới 50.000 người",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án khu đô thị có quy mô sử dụng đất dưới 300 ha và quy mô dân số dưới 50.000 người",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư xây dựng và kinh doanh sân gôn (golf)",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: "Dự án đầu tư của nhà đầu tư nước ngoài, tổ chức kinh tế có vốn đầu tư nước ngoài thực hiện tại đảo và xã, phường, thị trấn biên giới; xã, phường, thị trấn ven biển; khu vực khác có ảnh hưởng đến quốc phòng, an ninh.",
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
  {
    name: `Dự án đầu tư có các nội dung đầu tư ""không"" thuộc các nội dung trên và phù hợp các điều kiện quy định tại khoản 2 Điều 38 Luật đầu tư số 61/2020:
    a) Dự án đầu tư không thuộc ngành, nghề cấm đầu tư kinh doanh quy định tại Điều 10, Nghị định số 31/2021/NĐ-CP.
    b) Có địa điểm thực hiện dự án đầu tư.
    c) Dự án đầu tư phù hợp với quy hoạch quy định tại điểm a khoản 3 Điều 33 của Luật đầu tư số 61/2020.
    d) Đáp ứng điều kiện về suất đầu tư trên một diện tích đất, số lượng lao động sử dụng (nếu có).
    đ) Đáp ứng điều kiện tiếp cận thị trường đối với nhà đầu tư nước ngoài.`,
    city: "",
    isIndustrialArea: null,
    isFirst: null,
    isModified: null,
  },
]
